export interface State {
  name: string;
  districts: District[];
}

export interface District {
  name: string;
  taluks: string[];
}

export const INDIAN_STATES: State[] = [
  {
    name: "Andhra Pradesh",
    districts: [
      {
        name: "Anantapur",
        taluks: [
          "Anantapur",
          "Atmakur",
          "Beluguppa",
          "Brahmasamudram",
          "Bukkapatnam",
          "Dharmavaram",
          "Guntakal",
          "Hindupur",
          "Kadiri",
          "Kalyanadurgam",
        ],
      },
      {
        name: "Chittoor",
        taluks: [
          "Chittoor",
          "Chandragiri",
          "Madanapalle",
          "Tirupati",
          "Puttur",
          "Palamaner",
          "Punganur",
          "Srikalahasti",
          "Nagari",
          "Kuppam",
        ],
      },
      {
        name: "East Godavari",
        taluks: [
          "Kakinada",
          "Amalapuram",
          "Rajahmundry",
          "Peddapuram",
          "Ramachandrapuram",
          "Tuni",
          "Prathipadu",
          "Pithapuram",
          "Mandapeta",
          "Korukonda",
        ],
      },
      {
        name: "Guntur",
        taluks: [
          "Guntur",
          "Tenali",
          "Bapatla",
          "Narasaraopet",
          "Vinukonda",
          "Sattenapalle",
          "Repalle",
          "Chilakaluripet",
          "Mangalagiri",
          "Tadikonda",
        ],
      },
      {
        name: "Krishna",
        taluks: [
          "Vijayawada",
          "Machilipatnam",
          "Gudivada",
          "Jaggayyapeta",
          "Nuzvidu",
          "Tiruvuru",
          "Mylavaram",
          "Nandigama",
          "Kankipadu",
          "Vissannapet",
        ],
      },
      {
        name: "Kurnool",
        taluks: [
          "Kurnool",
          "Nandyal",
          "Adoni",
          "Yemmiganur",
          "Allagadda",
          "Pathikonda",
          "Dhone",
          "Banaganapalle",
          "Koilkuntla",
          "Mantralayam",
        ],
      },
      {
        name: "Nellore",
        taluks: [
          "Nellore",
          "Gudur",
          "Kavali",
          "Atmakur",
          "Venkatagiri",
          "Udayagiri",
          "Sullurpeta",
          "Buchireddipalem",
          "Dagadarthi",
          "Indukurpet",
        ],
      },
      {
        name: "Prakasam",
        taluks: [
          "Ongole",
          "Chirala",
          "Kandukur",
          "Markapur",
          "Giddalur",
          "Podili",
          "Kanigiri",
          "Darsi",
          "Addanki",
          "Santhanuthalapadu",
        ],
      },
      {
        name: "Srikakulam",
        taluks: [
          "Srikakulam",
          "Palakonda",
          "Narasannapeta",
          "Amadalavalasa",
          "Etcherla",
          "Hiramandalam",
          "Rajam",
          "Tekkali",
          "Pathapatnam",
          "Sompeta",
        ],
      },
      {
        name: "Visakhapatnam",
        taluks: [
          "Visakhapatnam",
          "Anakapalle",
          "Narsipatnam",
          "Yelamanchili",
          "Chodavaram",
          "Madugula",
          "Paderu",
          "Araku Valley",
          "Chintapalle",
          "Hukumpeta",
        ],
      },
      {
        name: "Vizianagaram",
        taluks: [
          "Vizianagaram",
          "Bobbili",
          "Cheepurupalle",
          "Gajapathinagaram",
          "Nellimarla",
          "Parvatipuram",
          "Parvathipuram",
          "Salur",
          "Srungavarapukota",
          "Vepada",
        ],
      },
      {
        name: "West Godavari",
        taluks: [
          "Eluru",
          "Bhimavaram",
          "Tadepalligudem",
          "Narasapuram",
          "Tanuku",
          "Nidadavole",
          "Kovvur",
          "Achanta",
          "Akividu",
          "Attili",
        ],
      },
      {
        name: "YSR Kadapa",
        taluks: [
          "Kadapa",
          "Proddatur",
          "Jammalamadugu",
          "Rayachoty",
          "Mydukur",
          "Pulivendula",
          "Badvel",
          "Rajampet",
          "Kamalapuram",
          "Yerraguntla",
        ],
      },
    ],
  },
  {
    name: "Arunachal Pradesh",
    districts: [
      { name: "Tawang", taluks: ["Tawang", "Lumla", "Mukto", "Jang", "Kitpi"] },
      {
        name: "West Kameng",
        taluks: ["Bomdila", "Kalaktang", "Thrizino", "Rupa", "Singchung"],
      },
      {
        name: "East Kameng",
        taluks: ["Seppa", "Chayang Tajo", "Pipu", "Bameng", "Richukrong"],
      },
      {
        name: "Papum Pare",
        taluks: ["Yupia", "Mengio", "Kimin", "Dollungmukh", "Sagalee"],
      },
      {
        name: "Kurung Kumey",
        taluks: ["Koloriang", "Nyapin", "Parsi Parlo", "Sangram", "Chambang"],
      },
    ],
  },
  {
    name: "Assam",
    districts: [
      {
        name: "Baksa",
        taluks: ["Mushalpur", "Barama", "Tamulpur", "Goreswar", "Jalah"],
      },
      {
        name: "Barpeta",
        taluks: ["Barpeta", "Bajali", "Pathsala", "Howly", "Mandia"],
      },
      {
        name: "Biswanath",
        taluks: [
          "Biswanath Chariali",
          "Behali",
          "Gohpur",
          "Jamuguri",
          "Baghmara",
        ],
      },
      {
        name: "Bongaigaon",
        taluks: [
          "Bongaigaon",
          "Bijni",
          "Chaprakata",
          "Dangtol",
          "North Salmara",
        ],
      },
      {
        name: "Cachar",
        taluks: ["Silchar", "Karimganj", "Hailakandi", "Lakhipur", "Udharbond"],
      },
    ],
  },
  {
    name: "Bihar",
    districts: [
      {
        name: "Araria",
        taluks: ["Araria", "Forbesganj", "Jokihat", "Kursakanta", "Narpatganj"],
      },
      {
        name: "Arwal",
        taluks: ["Arwal", "Karpi", "Kaler", "Sonbhadra Banshi", "Kurtha"],
      },
      {
        name: "Aurangabad",
        taluks: ["Aurangabad", "Daudnagar", "Goh", "Rafiganj", "Barun"],
      },
      {
        name: "Banka",
        taluks: ["Banka", "Amarpur", "Katoria", "Belhar", "Chandan"],
      },
      {
        name: "Begusarai",
        taluks: [
          "Begusarai",
          "Bachhwara",
          "Ballia",
          "Birpur",
          "Cheria-Bariarpur",
        ],
      },
    ],
  },
  {
    name: "Chhattisgarh",
    districts: [
      {
        name: "Balod",
        taluks: ["Balod", "Arjuni", "Dondi", "Gurur", "Lohara"],
      },
      {
        name: "Baloda Bazar",
        taluks: ["Baloda Bazar", "Bhatapara", "Bilha", "Kasdol", "Palari"],
      },
      {
        name: "Balrampur",
        taluks: ["Balrampur", "Kusmi", "Ramanujganj", "Samri", "Shankargarh"],
      },
      {
        name: "Bastar",
        taluks: ["Jagdalpur", "Bastar", "Bakawand", "Darbha", "Lohandiguda"],
      },
      {
        name: "Bemetara",
        taluks: ["Bemetara", "Berla", "Nawagarh", "Saja", "Thankhamharia"],
      },
    ],
  },
  {
    name: "Goa",
    districts: [
      {
        name: "North Goa",
        taluks: ["Bardez", "Bicholim", "Pernem", "Sattari", "Tiswadi"],
      },
      {
        name: "South Goa",
        taluks: [
          "Canacona",
          "Dharbandora",
          "Mormugao",
          "Quepem",
          "Salcete",
          "Sanguem",
        ],
      },
    ],
  },
  {
    name: "Gujarat",
    districts: [
      {
        name: "Ahmedabad",
        taluks: [
          "Ahmedabad City",
          "Ahmedabad Rural",
          "Daskroi",
          "Detroj-Rampura",
          "Dhandhuka",
        ],
      },
      {
        name: "Amreli",
        taluks: [
          "Amreli",
          "Babra",
          "Bagasara",
          "Dhari",
          "Jafrabad",
          "Khambha",
          "Kunkavav vadia",
          "Lathi",
          "Lilia",
          "Rajula",
          "Savarkundla",
        ],
      },
      {
        name: "Anand",
        taluks: [
          "Anand",
          "Borsad",
          "Khambhat",
          "Petlad",
          "Sojitra",
          "Tarapur",
          "Umreth",
          "Anklav",
        ],
      },
      {
        name: "Aravalli",
        taluks: ["Bayad", "Bhiloda", "Dhansura", "Malpur", "Meghraj", "Modasa"],
      },
      {
        name: "Banaskantha",
        taluks: [
          "Palanpur",
          "Abu Road",
          "Ambaji",
          "Bhabhar",
          "Danta",
          "Dantiwada",
          "Deesa",
          "Deodar",
          "Kankrej",
          "Lakhani",
          "Santalpur",
          "Siddhpur",
          "Tharad",
          "Vadgam",
          "Vav",
        ],
      },
    ],
  },
  {
    name: "Haryana",
    districts: [
      {
        name: "Ambala",
        taluks: ["Ambala", "Barara", "Naraingarh", "Shahzadpur"],
      },
      {
        name: "Bhiwani",
        taluks: ["Bhiwani", "Bawani Khera", "Loharu", "Siwani", "Tosham"],
      },
      { name: "Charkhi Dadri", taluks: ["Charkhi Dadri", "Badhra", "Jhajjar"] },
      {
        name: "Faridabad",
        taluks: ["Faridabad", "Ballabgarh", "Hathin", "Palwal"],
      },
      { name: "Fatehabad", taluks: ["Fatehabad", "Jakhal", "Ratia", "Tohana"] },
    ],
  },
  {
    name: "Himachal Pradesh",
    districts: [
      {
        name: "Bilaspur",
        taluks: ["Bilaspur", "Ghumarwin", "Jhandutta", "Sadar"],
      },
      {
        name: "Chamba",
        taluks: ["Chamba", "Bharmour", "Churah", "Dalhousie", "Pangi"],
      },
      {
        name: "Hamirpur",
        taluks: ["Hamirpur", "Barsar", "Bhoranj", "Nadaun", "Sujanpur"],
      },
      {
        name: "Kangra",
        taluks: [
          "Dharamshala",
          "Baijnath",
          "Baroh",
          "Dehra",
          "Fatehpur",
          "Indora",
          "Jawali",
          "Kangra",
          "Khundian",
          "Nagrota Bagwan",
          "Nurpur",
          "Palampur",
          "Rait",
          "Shahpur",
          "Sulah",
        ],
      },
      {
        name: "Kinnaur",
        taluks: [
          "Reckong Peo",
          "Hangrang",
          "Kalpa",
          "Morang",
          "Nichar",
          "Pooh",
        ],
      },
    ],
  },
  {
    name: "Jharkhand",
    districts: [
      {
        name: "Bokaro",
        taluks: [
          "Bermo",
          "Bokaro",
          "Chandankiyari",
          "Chas",
          "Gomia",
          "Jaridih",
        ],
      },
      {
        name: "Chatra",
        taluks: [
          "Chatra",
          "Hunterganj",
          "Itkhori",
          "Lawalong",
          "Mayurbhanj",
          "Pathalgada",
          "Pratappur",
          "Simaria",
          "Tandwa",
        ],
      },
      {
        name: "Deoghar",
        taluks: [
          "Deoghar",
          "Jasidih",
          "Karon",
          "Madhupur",
          "Mohanpur",
          "Palojori",
          "Sarwan",
          "Sonaraithari",
        ],
      },
      {
        name: "Dhanbad",
        taluks: [
          "Baghmara",
          "Baliapur",
          "Dhanbad",
          "Govindpur",
          "Jharia",
          "Nirsa",
          "Topchanchi",
        ],
      },
      {
        name: "Dumka",
        taluks: [
          "Dumka",
          "Gopikandar",
          "Jama",
          "Jarmundi",
          "Kathikund",
          "Masalia",
          "Ramgarh",
          "Ranishwar",
          "Saraiyahat",
          "Shikaripara",
        ],
      },
    ],
  },
  {
    name: "Karnataka",
    districts: [
      {
        name: "Bagalkot",
        taluks: [
          "Bagalkot",
          "Badami",
          "Bilagi",
          "Guledgudda",
          "Hungund",
          "Jamkhandi",
          "Mudhol",
          "Rabkavi Banhatti",
        ],
      },
      {
        name: "Ballari",
        taluks: [
          "Ballari",
          "Hadagalli",
          "Hagaribommanahalli",
          "Hospet",
          "Kudligi",
          "Sandur",
          "Siruguppa",
        ],
      },
      {
        name: "Belagavi",
        taluks: [
          "Belagavi",
          "Athni",
          "Bailhongal",
          "Chikodi",
          "Gokak",
          "Hukkeri",
          "Khanapur",
          "Raibag",
          "Ramadurg",
          "Savadatti",
        ],
      },
      {
        name: "Bengaluru Rural",
        taluks: ["Devanahalli", "Doddaballapura", "Hosakote", "Nelamangala"],
      },
      {
        name: "Bengaluru Urban",
        taluks: [
          "Anekal",
          "Bengaluru East",
          "Bengaluru North",
          "Bengaluru South",
        ],
      },
    ],
  },
  {
    name: "Kerala",
    districts: [
      {
        name: "Alappuzha",
        taluks: [
          "Alappuzha",
          "Ambalappuzha",
          "Chengannur",
          "Cherthala",
          "Karthikappally",
          "Kuttanad",
          "Mavelikkara",
        ],
      },
      {
        name: "Ernakulam",
        taluks: [
          "Aluva",
          "Kanayannur",
          "Kochi",
          "Kothamangalam",
          "Kunnathunad",
          "Muvattupuzha",
          "North Paravur",
          "Paravur",
        ],
      },
      {
        name: "Idukki",
        taluks: ["Devikulam", "Peermade", "Thodupuzha", "Udumbanchola"],
      },
      {
        name: "Kannur",
        taluks: ["Kannur", "Iritty", "Taliparamba", "Thalassery"],
      },
      { name: "Kasaragod", taluks: ["Kasaragod", "Hosdurg"] },
    ],
  },
  {
    name: "Madhya Pradesh",
    districts: [
      { name: "Agar Malwa", taluks: ["Agar", "Susner", "Nalkheda"] },
      {
        name: "Alirajpur",
        taluks: [
          "Alirajpur",
          "Bhabra",
          "Jobat",
          "Katthiwara",
          "Sondwa",
          "Udaygarh",
        ],
      },
      {
        name: "Anuppur",
        taluks: ["Anuppur", "Jaithari", "Kotma", "Pushprajgarh"],
      },
      {
        name: "Ashoknagar",
        taluks: ["Ashoknagar", "Chanderi", "Isagarh", "Mungaoli"],
      },
      {
        name: "Balaghat",
        taluks: [
          "Balaghat",
          "Baihar",
          "Birsa",
          "Katangi",
          "Khairlanji",
          "Lanji",
          "Paraswada",
          "Waraseoni",
        ],
      },
    ],
  },
  {
    name: "Maharashtra",
    districts: [
      {
        name: "Ahmednagar",
        taluks: [
          "Ahmednagar",
          "Akole",
          "Jamkhed",
          "Karjat",
          "Kopargaon",
          "Nagar",
          "Nevasa",
          "Parner",
          "Pathardi",
          "Rahata",
          "Rahuri",
          "Sangamner",
          "Shevgaon",
          "Shrigonda",
        ],
      },
      {
        name: "Akola",
        taluks: [
          "Akola",
          "Akot",
          "Balapur",
          "Barshitakli",
          "Murtijapur",
          "Patur",
          "Telhara",
        ],
      },
      {
        name: "Amravati",
        taluks: [
          "Amravati",
          "Achalpur",
          "Anjangaon Surji",
          "Bhatkuli",
          "Chandur Bazar",
          "Chandur Railway",
          "Chikhaldara",
          "Churni",
          "Daryapur",
          "Dharni",
          "Dhamangaon Railway",
          "Morshi",
          "Nandgaon Khandeshwar",
          "Teosa",
          "Warud",
        ],
      },
      {
        name: "Aurangabad",
        taluks: [
          "Aurangabad",
          "Gangapur",
          "Kannad",
          "Khultabad",
          "Paithan",
          "Phulambri",
          "Sillod",
          "Soegaon",
          "Vaijapur",
        ],
      },
      {
        name: "Beed",
        taluks: [
          "Beed",
          "Ambajogai",
          "Ashti",
          "Georai",
          "Kaij",
          "Majalgaon",
          "Parli",
          "Patoda",
          "Shirur-Kasar",
          "Wadwani",
        ],
      },
    ],
  },
  {
    name: "Manipur",
    districts: [
      { name: "Bishnupur", taluks: ["Bishnupur", "Moirang", "Nambol"] },
      { name: "Chandel", taluks: ["Chandel", "Chakpikarong", "Tengnoupal"] },
      { name: "Churachandpur", taluks: ["Churachandpur", "Lamka", "Singngat"] },
      { name: "Imphal East", taluks: ["Porompat", "Jiribam", "Wangoi"] },
      { name: "Imphal West", taluks: ["Lamphelpat", "Patsoi", "Wangoi"] },
    ],
  },
  {
    name: "Meghalaya",
    districts: [
      {
        name: "East Garo Hills",
        taluks: ["Williamnagar", "Rongjeng", "Samanda"],
      },
      {
        name: "East Jaintia Hills",
        taluks: ["Khliehriat", "Saipung", "Thadlaskein"],
      },
      {
        name: "East Khasi Hills",
        taluks: ["Shillong", "Mawkyrwat", "Pynursla"],
      },
      {
        name: "North Garo Hills",
        taluks: ["Resubelpara", "Bajengdoba", "Tikrikilla"],
      },
      { name: "Ri Bhoi", taluks: ["Nongpoh", "Mawthadraishan", "Umsning"] },
    ],
  },
  {
    name: "Mizoram",
    districts: [
      { name: "Aizawl", taluks: ["Aizawl", "Darlawn", "Thingsulthliah"] },
      { name: "Champhai", taluks: ["Champhai", "Khawzawl", "Ngopa"] },
      { name: "Kolasib", taluks: ["Kolasib", "Bilkhawthlir", "Thingdawl"] },
      { name: "Lawngtlai", taluks: ["Lawngtlai", "Sangau", "Chawngte"] },
      { name: "Lunglei", taluks: ["Lunglei", "Hnahthial", "Tlabung"] },
    ],
  },
  {
    name: "Nagaland",
    districts: [
      { name: "Dimapur", taluks: ["Dimapur", "Chumukedima", "Dhansiripar"] },
      { name: "Kiphire", taluks: ["Kiphire", "Longmatra", "Pungro"] },
      { name: "Kohima", taluks: ["Kohima", "Jakhama", "Sechu-Zubza"] },
      { name: "Longleng", taluks: ["Longleng", "Mon", "Tamlu"] },
      { name: "Mokokchung", taluks: ["Mokokchung", "Alongkima", "Koridang"] },
    ],
  },
  {
    name: "Odisha",
    districts: [
      {
        name: "Angul",
        taluks: [
          "Angul",
          "Athamallik",
          "Banarpal",
          "Chhendipada",
          "Kaniha",
          "Kishorenagar",
          "Pallahara",
          "Talcher",
        ],
      },
      {
        name: "Balangir",
        taluks: [
          "Balangir",
          "Agalpur",
          "Belpada",
          "Deogaon",
          "Khaprakhol",
          "Loisinga",
          "Muribahal",
          "Patnagarh",
          "Saintala",
          "Titlagarh",
          "Turekela",
        ],
      },
      {
        name: "Balasore",
        taluks: [
          "Balasore",
          "Basta",
          "Bhograi",
          "Jaleswar",
          "Nilagiri",
          "Oupada",
          "Remuna",
          "Simulia",
          "Soro",
        ],
      },
      {
        name: "Bargarh",
        taluks: [
          "Bargarh",
          "Ambabhona",
          "Attabira",
          "Barpali",
          "Bheden",
          "Bijepur",
          "Gaisilet",
          "Padampur",
          "Paikmal",
        ],
      },
      {
        name: "Bhadrak",
        taluks: [
          "Bhadrak",
          "Basudevpur",
          "Bonth",
          "Chandbali",
          "Dhamnagar",
          "Tihidi",
          "Were",
        ],
      },
    ],
  },
  {
    name: "Punjab",
    districts: [
      {
        name: "Amritsar",
        taluks: [
          "Amritsar-I",
          "Amritsar-II",
          "Ajnala",
          "Majitha",
          "Rayya",
          "Tarn Taran",
        ],
      },
      { name: "Barnala", taluks: ["Barnala", "Mehal Kalan", "Tapa"] },
      {
        name: "Bathinda",
        taluks: ["Bathinda", "Rampura Phul", "Talwandi Sabo"],
      },
      { name: "Faridkot", taluks: ["Faridkot", "Jaitu", "Kotkapura"] },
      {
        name: "Fatehgarh Sahib",
        taluks: [
          "Amloh",
          "Bassi Pathana",
          "Fatehgarh Sahib",
          "Khamano",
          "Sirhind",
        ],
      },
    ],
  },
  {
    name: "Rajasthan",
    districts: [
      {
        name: "Ajmer",
        taluks: [
          "Ajmer",
          "Beawar",
          "Kekri",
          "Kishangarh",
          "Masuda",
          "Nasirabad",
          "Pisangan",
          "Silora",
        ],
      },
      {
        name: "Alwar",
        taluks: [
          "Alwar",
          "Bansur",
          "Behror",
          "Kathumar",
          "Khairthal",
          "Kishangarh Bas",
          "Lachhmangarh",
          "Mundawar",
          "Neemrana",
          "Rajgarh",
          "Ramgarh",
          "Thanagazi",
          "Tijara",
        ],
      },
      {
        name: "Banswara",
        taluks: [
          "Banswara",
          "Bagidora",
          "Garhi",
          "Ghatol",
          "Kushalgarh",
          "Sajjangarh",
        ],
      },
      {
        name: "Baran",
        taluks: [
          "Baran",
          "Antah",
          "Atru",
          "Chhabra",
          "Chhipabarod",
          "Kishanganj",
          "Mangrol",
          "Shahbad",
        ],
      },
      {
        name: "Barmer",
        taluks: [
          "Barmer",
          "Balotra",
          "Baytoo",
          "Chohtan",
          "Dhorimanna",
          "Gadra Road",
          "Guda Malani",
          "Pachpadra",
          "Ramsar",
          "Sedwa",
          "Sheo",
          "Siwana",
        ],
      },
    ],
  },
  {
    name: "Sikkim",
    districts: [
      {
        name: "East Sikkim",
        taluks: ["Gangtok", "Pakyong", "Rongli", "Ranipool"],
      },
      {
        name: "North Sikkim",
        taluks: ["Mangan", "Chungthang", "Lachen", "Lachung"],
      },
      {
        name: "South Sikkim",
        taluks: ["Namchi", "Ravangla", "Jorethang", "Yangang"],
      },
      {
        name: "West Sikkim",
        taluks: ["Gyalshing", "Dentam", "Daramdin", "Soreng"],
      },
    ],
  },
  {
    name: "Tamil Nadu",
    districts: [
      {
        name: "Ariyalur",
        taluks: ["Ariyalur", "Andimadam", "Sendurai", "Udayarpalayam"],
      },
      {
        name: "Chennai",
        taluks: [
          "Alandur",
          "Ambattur",
          "Aminjikarai",
          "Anna Nagar",
          "Egmore",
          "Guindy",
          "Madhavaram",
          "Madhuravoyal",
          "Manali",
          "Mylapore",
          "Perambur",
          "Purasawalkam",
          "Sholinganallur",
          "Thiruvottiyur",
          "Tondiarpet",
        ],
      },
      {
        name: "Coimbatore",
        taluks: [
          "Avinashi",
          "Coimbatore North",
          "Coimbatore South",
          "Kinathukadavu",
          "Madukkarai",
          "Mettupalayam",
          "Perur",
          "Pollachi",
          "Sulur",
          "Valparai",
        ],
      },
      {
        name: "Cuddalore",
        taluks: [
          "Cuddalore",
          "Bhuvanagiri",
          "Chidambaram",
          "Kattumannarkoil",
          "Kurinjipadi",
          "Panruti",
          "Srimushnam",
          "Titakudi",
          "Veppur",
          "Virudhachalam",
          "Vridhachalam",
        ],
      },
      {
        name: "Dharmapuri",
        taluks: [
          "Dharmapuri",
          "Harur",
          "Karimangalam",
          "Nallampalli",
          "Palacode",
          "Pennagaram",
        ],
      },
    ],
  },
  {
    name: "Telangana",
    districts: [
      {
        name: "Adilabad",
        taluks: [
          "Adilabad",
          "Bela",
          "Bhainsa",
          "Boath",
          "Ichoda",
          "Jainoor",
          "Kerameri",
          "Kuntala",
          "Mudhole",
          "Narnoor",
          "Nirmal",
          "Tamsi",
          "Tandur",
          "Utnoor",
          "Vemanpalle",
          "Wankidi",
        ],
      },
      {
        name: "Bhadradri Kothagudem",
        taluks: [
          "Kothagudem",
          "Aswapuram",
          "Bhadrachalam",
          "Burgampahad",
          "Chunchupalle",
          "Dummagudem",
          "Julurpadu",
          "Karakagudem",
          "Kukunoor",
          "Manuguru",
          "Pinapaka",
          "Tekulapalle",
          "Yellandu",
        ],
      },
      { name: "Hyderabad", taluks: ["Hyderabad", "Secunderabad"] },
      {
        name: "Jagtial",
        taluks: [
          "Jagtial",
          "Dharmapuri",
          "Gollapalle",
          "Ibrahimpatnam",
          "Kathlapur",
          "Korutla",
          "Mallapur",
          "Metpalle",
          "Pegadapalle",
          "Raikal",
          "Sarangapur",
          "Velgatoor",
        ],
      },
      {
        name: "Jangaon",
        taluks: [
          "Jangaon",
          "Bachannapet",
          "Chityal",
          "Devaruppula",
          "Ghanpur (Station)",
          "Kodakandla",
          "Lingalaghanpur",
          "Nallabelly",
          "Palakurthi",
          "Raghunathpalle",
          "Station Ghanpur",
          "Zaffergadh",
        ],
      },
    ],
  },
  {
    name: "Tripura",
    districts: [
      {
        name: "Dhalai",
        taluks: [
          "Ambassa",
          "Chawmanu",
          "Dumburnagar",
          "Kamalpur",
          "Longtharai Valley",
          "Manu",
          "Salema",
        ],
      },
      {
        name: "Gomati",
        taluks: [
          "Udaipur",
          "Amarpur",
          "Karbook",
          "Melaghar",
          "Ompi",
          "Rajnagar",
        ],
      },
      { name: "Khowai", taluks: ["Khowai", "Kalyanpur", "Teliamura"] },
      {
        name: "North Tripura",
        taluks: [
          "Dharmanagar",
          "Dasda",
          "Kailashahar",
          "Kanchanpur",
          "Panisagar",
        ],
      },
      {
        name: "Sepahijala",
        taluks: ["Bishramganj", "Boxanagar", "Melaghar", "Sonamura"],
      },
    ],
  },
  {
    name: "Uttar Pradesh",
    districts: [
      {
        name: "Agra",
        taluks: ["Agra", "Fatehabad", "Fatehpur Sikri", "Kheragarh", "Kiraoli"],
      },
      {
        name: "Aligarh",
        taluks: [
          "Aligarh",
          "Atrauli",
          "Gabhana",
          "Iglas",
          "Khair",
          "Koil",
          "Sikandra Rao",
        ],
      },
      {
        name: "Allahabad",
        taluks: [
          "Allahabad",
          "Bara",
          "Chaka",
          "Handia",
          "Jasra",
          "Karchhana",
          "Koraon",
          "Meja",
          "Phulpur",
          "Sadar",
          "Shankargarh",
          "Soraon",
        ],
      },
      {
        name: "Ambedkar Nagar",
        taluks: ["Akbarpur", "Bhiti", "Jalalpur", "Tanda"],
      },
      {
        name: "Amethi",
        taluks: ["Gauriganj", "Jagdishpur", "Musafirkhana", "Tiloi"],
      },
    ],
  },
  {
    name: "Uttarakhand",
    districts: [
      {
        name: "Almora",
        taluks: [
          "Almora",
          "Bhaisiachhana",
          "Bhikiyasain",
          "Chaukhutiya",
          "Dwarahat",
          "Hawalbagh",
          "Lamgara",
          "Ranikhet",
          "Salt",
          "Someshwar",
          "Syalde",
          "Takula",
        ],
      },
      { name: "Bageshwar", taluks: ["Bageshwar", "Garur", "Kanda"] },
      {
        name: "Chamoli",
        taluks: [
          "Chamoli Gopeshwar",
          "Dasholi",
          "Gairsain",
          "Joshimath",
          "Karnaprayag",
          "Narayanbagar",
          "Pokhari",
          "Tharali",
        ],
      },
      {
        name: "Champawat",
        taluks: ["Champawat", "Barakot", "Lohaghat", "Pati"],
      },
      {
        name: "Dehradun",
        taluks: [
          "Dehradun",
          "Chakrata",
          "Kalsi",
          "Mussoorie",
          "Rajpur",
          "Raipur",
          "Sahaspur",
          "Vikasnagar",
        ],
      },
    ],
  },
  {
    name: "West Bengal",
    districts: [
      {
        name: "Alipurduar",
        taluks: [
          "Alipurduar-I",
          "Alipurduar-II",
          "Falakata",
          "Kalchini",
          "Kumargram",
          "Madarihat",
        ],
      },
      {
        name: "Bankura",
        taluks: [
          "Bankura-I",
          "Bankura-II",
          "Barjora",
          "Chhatna",
          "Gangajalghati",
          "Hirbandh",
          "Indpur",
          "Joypur",
          "Khatra",
          "Mejhia",
          "Onda",
          "Patrasayer",
          "Raipur",
          "Ranibandh",
          "Saltora",
          "Simlapal",
          "Sonamukhi",
          "Taldangra",
        ],
      },
      {
        name: "Birbhum",
        taluks: [
          "Bolpur-Sriniketan",
          "Dubrajpur",
          "Ilambazar",
          "Khoyrasole",
          "Labhpur",
          "Mayureswar-I",
          "Mayureswar-II",
          "Murarai-I",
          "Murarai-II",
          "Nalhati-I",
          "Nalhati-II",
          "Nanoor",
          "Rajnagar",
          "Rampurhat-I",
          "Rampurhat-II",
          "Sainthia",
          "Suri-I",
          "Suri-II",
        ],
      },
      {
        name: "Cooch Behar",
        taluks: [
          "Cooch Behar-I",
          "Cooch Behar-II",
          "Dinhata-I",
          "Dinhata-II",
          "Mathabhanga-I",
          "Mathabhanga-II",
          "Mekhliganj",
          "Sitai",
          "Sitalkuchi",
          "Tufanganj-I",
          "Tufanganj-II",
        ],
      },
      {
        name: "Darjeeling",
        taluks: [
          "Darjeeling-Pulbazar",
          "Jorebunglow-Sukhiapokhri",
          "Kalimpong-I",
          "Kalimpong-II",
          "Kharibari",
          "Kurseong",
          "Matigara-Naxalbari",
          "Mirik",
          "Phansidewa",
          "Rangli-Rangliot",
        ],
      },
    ],
  },
];
